apiVersion: middleware.cn/v1
kind: MiddlewareConfiguration
metadata:
  name: rabbitmq-rolebinding
spec:
  template: |
    kind: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: "{{ .Globe.Name }}-rabbitmq-peer-discovery-rbac"
    subjects:
      - kind: ServiceAccount
        name: "{{ .Globe.Name }}-rabbitmq"
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: "{{ .Globe.Name }}-rabbitmq-peer-discovery-rbac"